using System;
using System.Runtime.InteropServices;

// Autogenerated @ 24/05/18
namespace InterfaceArgonCore
{
    /// <summary>
    /// Exports the delegates for all interfaces that implement ArgonCore
    /// </summary>
    [ArgonCore.Interface.Delegate(Name = "ArgonCore")]
    class ArgonCore_Delegates
    {
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate IntPtr CreateInterfaceDelegate(IntPtr _, string name);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate bool GetCallbackDelegate(IntPtr _, ref ArgonCore.Client.CallbackMsg c);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate void FreeLastCallbackDelegate(IntPtr _);
    }
}
