using System;
using System.Runtime.InteropServices;

// Autogenerated @ 26/05/18
namespace InterfaceArgonCore
{
    /// <summary>
    /// Exports the delegates for all interfaces that implement ArgonCore
    /// </summary>
    [ArgonCore.Interface.Delegate(Name = "ArgonCore")]
    class ArgonCore_Delegates
    {
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate IntPtr CreateInterfaceDelegate(IntPtr _, int pipe_id, string name);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate IntPtr CreateInterfaceNoPipeDelegate(IntPtr _, string name);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate bool GetCallbackDelegate(IntPtr _, int pipe_id, ref ArgonCore.Client.CallbackMsg c);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate void FreeLastCallbackDelegate(IntPtr _, int pipe_id);
    }
}
