using System;
using System.Runtime.InteropServices;

// Autogenerated @ 26/05/18
namespace InterfaceMusic
{
    /// <summary>
    /// Exports the delegates for all interfaces that implement SteamMusic
    /// </summary>
    [ArgonCore.Interface.Delegate(Name = "SteamMusic")]
    class SteamMusic_Delegates
    {
    }
}
