using System;

// Autogenerated @ 22/05/18
namespace InterfaceAppList
{
    /// <summary>
    /// Exports the delegates for all interfaces that implement SteamAppList
    /// </summary>
    [ArgonCore.Interface.Delegate(Name = "SteamAppList")]
    class SteamAppList_Delegates
    {
    }
}
