using System;
using System.Runtime.InteropServices;

// Autogenerated @ 23/05/18
namespace InterfaceUnifiedMessages
{
    /// <summary>
    /// Exports the delegates for all interfaces that implement SteamUnifiedMessages
    /// </summary>
    [ArgonCore.Interface.Delegate(Name = "SteamUnifiedMessages")]
    class SteamUnifiedMessages_Delegates
    {
    }
}
