using System;
using System.Runtime.InteropServices;

// Autogenerated @ 23/05/18
namespace InterfaceVideo
{
    /// <summary>
    /// Exports the delegates for all interfaces that implement SteamVideo
    /// </summary>
    [ArgonCore.Interface.Delegate(Name = "SteamVideo")]
    class SteamVideo_Delegates
    {
    }
}
