using System;

// Autogenerated @ 23/05/18
namespace InterfaceInventory
{
    /// <summary>
    /// Exports the delegates for all interfaces that implement SteamInventory
    /// </summary>
    [ArgonCore.Interface.Delegate(Name = "SteamInventory")]
    class SteamInventory_Delegates
    {
    }
}
