using System;

// Autogenerated @ 21/05/18
namespace InterfaceMusic
{
    /// <summary>
    /// Exports the delegates for all interfaces that implement SteamMusic001
    /// </summary>
    [ArgonCore.Interface.Delegate(Name = "SteamMusic001")]
    class SteamMusic001_Delegates
    {
    }
}
