using System;
using System.Runtime.InteropServices;

// Autogenerated @ 09/06/18
namespace InterfaceFriends
{
    /// <summary>
    /// Exports the delegates for all interfaces that implement SteamFriends
    /// </summary>
    [ArgonCore.Interface.Delegate(Name = "SteamFriends")]
    class SteamFriends_Delegates
    {
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate string GetPersonaNameDelegate(IntPtr _);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate uint GetPersonaStateDelegate(IntPtr _);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate void SetPersonaStateDelegate(IntPtr _, uint state);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate bool AddFriendDelegate(IntPtr _, ulong steam_id);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate bool RemoveFriendDelegate(IntPtr _, ulong steam_id);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate bool HasFriendDelegate(IntPtr _, ulong steam_id);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate uint GetFriendRelationshipDelegate(IntPtr _, ulong steam_id);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate uint GetFriendPersonaStateDelegate(IntPtr _, ulong steam_id);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate bool Deprecated_GetFriendGamePlayedDelegate(IntPtr _, ulong steam_id, ref System.UInt32 app_id, ref System.UInt32 game_ip, ref System.UInt32 game_port);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate string GetFriendPersonaNameDelegate(IntPtr _, ulong steam_id);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate int AddFriendByNameDelegate(IntPtr _, string name);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate int GetFriendCountDelegate(IntPtr _);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate ulong GetFriendByIndexDelegate(IntPtr _, int index);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate void SendMsgToFriendDelegate(IntPtr _, ulong dest_steam_id, uint msg_type, string message_body);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate void SetFriendRegValueDelegate(IntPtr _, ulong steam_id, string key, string value);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate string GetFriendRegValueDelegate(IntPtr _, ulong steam_id, string key);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate string GetFriendPersonaNameHistoryDelegate(IntPtr _, ulong steam_id, int index);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate int GetChatMessageDelegate(IntPtr _, ulong steam_id, int msg_index, IntPtr msg_out, int max_msg, ref System.UInt32 msg_type);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate int GetChatIDOfChatHistoryStartDelegate(IntPtr _, ulong steam_id);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate void SetChatHistoryStartDelegate(IntPtr _, ulong steam_id, int index);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate void ClearChatHistoryDelegate(IntPtr _, ulong steam_id);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate int InviteFriendByEmailDelegate(IntPtr _, string email);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate int GetBlockedFriendCountDelegate(IntPtr _);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate bool GetFriendGamePlayedDelegate(IntPtr _, ulong steam_id, ref System.UInt64 game_id, ref System.UInt32 server_ip, ref System.UInt16 server_port);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate bool GetFriendGamePlayed2Delegate(IntPtr _, ulong steam_id, ref System.UInt64 game_id, ref System.UInt32 server_ip, ref System.UInt16 server_port);
    }
}
