using System;

// Autogenerated @ 22/05/18
namespace InterfaceApps
{
    /// <summary>
    /// Exports the delegates for all interfaces that implement SteamApps
    /// </summary>
    [ArgonCore.Interface.Delegate(Name = "SteamApps")]
    class SteamApps_Delegates
    {
    }
}
