using System;
using System.Runtime.InteropServices;

// Autogenerated @ 01/06/18
namespace InterfaceFriends
{
    /// <summary>
    /// Exports the delegates for all interfaces that implement SteamFriends
    /// </summary>
    [ArgonCore.Interface.Delegate(Name = "SteamFriends")]
    class SteamFriends_Delegates
    {
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate string GetPersonaNameDelegate(IntPtr _);
    }
}
