using System;
using System.Runtime.InteropServices;

// Autogenerated @ 09/06/18
namespace InterfaceInventory
{
    /// <summary>
    /// Exports the delegates for all interfaces that implement SteamInventory
    /// </summary>
    [ArgonCore.Interface.Delegate(Name = "SteamInventory")]
    class SteamInventory_Delegates
    {
    }
}
