using System;
using System.Runtime.InteropServices;

// Autogenerated @ 02/06/18
namespace InterfaceRemoteStorage
{
    /// <summary>
    /// Exports the delegates for all interfaces that implement SteamRemoteStorage
    /// </summary>
    [ArgonCore.Interface.Delegate(Name = "SteamRemoteStorage")]
    class SteamRemoteStorage_Delegates
    {
    }
}
