using System;

// Autogenerated @ 22/05/18
namespace InterfaceScreenshots
{
    /// <summary>
    /// Exports the delegates for all interfaces that implement SteamScreenshots
    /// </summary>
    [ArgonCore.Interface.Delegate(Name = "SteamScreenshots")]
    class SteamScreenshots_Delegates
    {
    }
}
