using System;

// Autogenerated @ 23/05/18
namespace InterfaceUGC
{
    /// <summary>
    /// Exports the delegates for all interfaces that implement SteamUGC
    /// </summary>
    [ArgonCore.Interface.Delegate(Name = "SteamUGC")]
    class SteamUGC_Delegates
    {
    }
}
