using System;
using System.Runtime.InteropServices;

// Autogenerated @ 23/05/18
namespace InterfaceMusicRemote
{
    /// <summary>
    /// Exports the delegates for all interfaces that implement SteamMusicRemote
    /// </summary>
    [ArgonCore.Interface.Delegate(Name = "SteamMusicRemote")]
    class SteamMusicRemote_Delegates
    {
    }
}
