using System;
using System.Runtime.InteropServices;

// Autogenerated @ 01/06/18
namespace InterfaceUtils
{
    /// <summary>
    /// Exports the delegates for all interfaces that implement SteamUtils
    /// </summary>
    [ArgonCore.Interface.Delegate(Name = "SteamUtils")]
    class SteamUtils_Delegates
    {
    }
}
