using System;

// Autogenerated @ 22/05/18
namespace InterfaceMusic
{
    /// <summary>
    /// Exports the delegates for all interfaces that implement SteamMusic
    /// </summary>
    [ArgonCore.Interface.Delegate(Name = "SteamMusic")]
    class SteamMusic_Delegates
    {
    }
}
