using System;
using System.Runtime.InteropServices;

// Autogenerated @ 30/05/18
namespace IntefaceNetworking
{
    /// <summary>
    /// Exports the delegates for all interfaces that implement SteamNetworking
    /// </summary>
    [ArgonCore.Interface.Delegate(Name = "SteamNetworking")]
    class SteamNetworking_Delegates
    {
    }
}
