using System;

// Autogenerated @ 22/05/18
namespace InterfaceMusicRemote
{
    /// <summary>
    /// Exports the delegates for all interfaces that implement SteamMusicRemote
    /// </summary>
    [ArgonCore.Interface.Delegate(Name = "SteamMusicRemote")]
    class SteamMusicRemote_Delegates
    {
    }
}
