using System;

// Autogenerated @ 22/05/18
namespace InterfaceGameServer
{
    /// <summary>
    /// Exports the delegates for all interfaces that implement SteamGameServer
    /// </summary>
    [ArgonCore.Interface.Delegate(Name = "SteamGameServer")]
    class SteamGameServer_Delegates
    {
    }
}
