using System;
using System.Runtime.InteropServices;

// Autogenerated @ 26/05/18
namespace InterfaceGameServerStats
{
    /// <summary>
    /// Exports the delegates for all interfaces that implement SteamGameServerStats
    /// </summary>
    [ArgonCore.Interface.Delegate(Name = "SteamGameServerStats")]
    class SteamGameServerStats_Delegates
    {
    }
}
