using System;

// Autogenerated @ 22/05/18
namespace InterfaceController
{
    /// <summary>
    /// Exports the delegates for all interfaces that implement SteamController
    /// </summary>
    [ArgonCore.Interface.Delegate(Name = "SteamController")]
    class SteamController_Delegates
    {
    }
}
