using System;
using System.Runtime.InteropServices;

// Autogenerated @ 11/08/18
namespace InterfaceArgonCore
{
    /// <summary>
    /// Exports the delegates for all interfaces that implement ArgonClient001
    /// </summary>
    [ArgonCore.Interface.Delegate(Name = "ArgonClient001")]
    class ArgonClient001_Delegates
    {
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate IntPtr CreateInterface(IntPtr _, int pipe_id, string name);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate IntPtr CreateInterfaceNoPipe(IntPtr _, string name);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate bool GetCallback(IntPtr _, int pipe_id, ref ArgonCore.IPC.CallbackMsg c);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate void FreeLastCallback(IntPtr _, int pipe_id);
    }
}
