using System;

// Autogenerated @ 07/05/18
namespace InterfaceArgonCore
{
    /// <summary>
    /// Exports the delegates for all interfaces that implement ArgonCore
    /// </summary>
    [ArgonCore.Interface.Delegate(Name = "ArgonCore")]
    class ArgonCore_Delegates
    {
        public delegate IntPtr CreateInterfaceDelegate(string name);
    }
}
