using System;
using System.Runtime.InteropServices;

// Autogenerated @ 14/07/18
namespace InterfaceArgonCore
{
    /// <summary>
    /// Exports the delegates for all interfaces that implement ArgonClient
    /// </summary>
    [ArgonCore.Interface.Delegate(Name = "ArgonClient")]
    class ArgonClient_Delegates
    {
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate IntPtr CreateInterfaceDelegate(IntPtr _, int pipe_id, string name);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate IntPtr CreateInterfaceNoPipeDelegate(IntPtr _, string name);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate bool GetCallbackDelegate(IntPtr _, int pipe_id, ref ArgonCore.IPC.CallbackMsg c);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate void FreeLastCallbackDelegate(IntPtr _, int pipe_id);
    }
}
