using System;
using System.Runtime.InteropServices;

// Autogenerated @ 06/08/18
namespace InterfaceMatchmaking
{
    /// <summary>
    /// Exports the delegates for all interfaces that implement SteamMatchmaking009
    /// </summary>
    [ArgonCore.Interface.Delegate(Name = "SteamMatchmaking009")]
    class SteamMatchmaking009_Delegates
    {
    }
}
