using System;
using System.Runtime.InteropServices;

// Autogenerated @ 21/07/18
namespace InterfaceGameServer
{
    /// <summary>
    /// Exports the delegates for all interfaces that implement SteamGameServer
    /// </summary>
    [ArgonCore.Interface.Delegate(Name = "SteamGameServer")]
    class SteamGameServer_Delegates
    {
    }
}
