using System;
using System.Runtime.InteropServices;

// Autogenerated @ 23/07/18
namespace InterfaceAppList
{
    /// <summary>
    /// Exports the delegates for all interfaces that implement SteamAppList001
    /// </summary>
    [ArgonCore.Interface.Delegate(Name = "SteamAppList001")]
    class SteamAppList001_Delegates
    {
    }
}
