using System;
using System.Runtime.InteropServices;

// Autogenerated @ 23/07/18
namespace InterfaceMatchmakingServers
{
    /// <summary>
    /// Exports the delegates for all interfaces that implement SteamMatchmakingServers002
    /// </summary>
    [ArgonCore.Interface.Delegate(Name = "SteamMatchmakingServers002")]
    class SteamMatchmakingServers002_Delegates
    {
    }
}
