using System;
using System.Runtime.InteropServices;

// Autogenerated @ 11/08/18
namespace InterfaceApps
{
    /// <summary>
    /// Exports the delegates for all interfaces that implement SteamApps008
    /// </summary>
    [ArgonCore.Interface.Delegate(Name = "SteamApps008")]
    class SteamApps008_Delegates
    {
    }
}
