using System;
using System.Runtime.InteropServices;

// Autogenerated @ 21/07/18
namespace InterfaceMatchmakingServers
{
    /// <summary>
    /// Exports the delegates for all interfaces that implement SteamMatchmakingServers
    /// </summary>
    [ArgonCore.Interface.Delegate(Name = "SteamMatchmakingServers")]
    class SteamMatchmakingServers_Delegates
    {
    }
}
