using System;
using System.Runtime.InteropServices;

// Autogenerated @ 14/07/18
namespace InterfaceScreenshots
{
    /// <summary>
    /// Exports the delegates for all interfaces that implement SteamScreenshots
    /// </summary>
    [ArgonCore.Interface.Delegate(Name = "SteamScreenshots")]
    class SteamScreenshots_Delegates
    {
    }
}
