using System;
using System.Runtime.InteropServices;

// Autogenerated @ 14/07/18
namespace InterfaceMatchmaking
{
    /// <summary>
    /// Exports the delegates for all interfaces that implement SteamMatchmaking
    /// </summary>
    [ArgonCore.Interface.Delegate(Name = "SteamMatchmaking")]
    class SteamMatchmaking_Delegates
    {
    }
}
