using System;
using System.Runtime.InteropServices;

// Autogenerated @ 11/08/18
namespace InterfaceVideo
{
    /// <summary>
    /// Exports the delegates for all interfaces that implement SteamVideo002
    /// </summary>
    [ArgonCore.Interface.Delegate(Name = "SteamVideo002")]
    class SteamVideo002_Delegates
    {
    }
}
