using System;
using System.Runtime.InteropServices;

// Autogenerated @ 19/07/18
namespace InterfaceHTTP
{
    /// <summary>
    /// Exports the delegates for all interfaces that implement SteamHTTP
    /// </summary>
    [ArgonCore.Interface.Delegate(Name = "SteamHTTP")]
    class SteamHTTP_Delegates
    {
    }
}
