using System;
using System.Runtime.InteropServices;

// Autogenerated @ 19/07/18
namespace InterfaceUserStats
{
    /// <summary>
    /// Exports the delegates for all interfaces that implement SteamUserStats
    /// </summary>
    [ArgonCore.Interface.Delegate(Name = "SteamUserStats")]
    class SteamUserStats_Delegates
    {
    }
}
