using System;
using System.Runtime.InteropServices;

// Autogenerated @ 06/08/18
namespace InterfaceController
{
    /// <summary>
    /// Exports the delegates for all interfaces that implement SteamController006
    /// </summary>
    [ArgonCore.Interface.Delegate(Name = "SteamController006")]
    class SteamController006_Delegates
    {
    }
}
