using System;
using System.Runtime.InteropServices;

// Autogenerated @ 06/08/18
namespace InterfaceInventory
{
    /// <summary>
    /// Exports the delegates for all interfaces that implement SteamInventory003
    /// </summary>
    [ArgonCore.Interface.Delegate(Name = "SteamInventory003")]
    class SteamInventory003_Delegates
    {
    }
}
