using System;

// Autogenerated @ 05/05/18
namespace InterfaceSteamClient
{
    /// <summary>
    /// Exports the delegates for all interfaces that implement SteamClient
    /// </summary>
    [ArgonCore.InterfaceDelegate(Name = "SteamClient")]
    class SteamClient_Delegates
    {
        public delegate IntPtr CreateSteamPipeDelegate();
        public delegate Boolean ReleaseSteamPipeDelegate(IntPtr pipe);
        public delegate IntPtr ConnectToGlobalUserDelegate(IntPtr pipe);
        public delegate IntPtr CreateLocalUserDelegate(ref IntPtr user, uint account_type);
        public delegate void ReleaseUserDelegate(IntPtr user, IntPtr pipe);
        public delegate IntPtr GetSteamUserDelegate(IntPtr user, IntPtr pipe, string version);
        public delegate IntPtr GetSteamGameServerDelegate(IntPtr user, IntPtr pipe, string version);
        public delegate void SetLocalIPBindingDelegate(uint ip, uint port);
        public delegate IntPtr GetSteamFriendsDelegate(IntPtr user, IntPtr pipe, string version);
        public delegate IntPtr GetSteamUtilsDelegate(IntPtr pipe, string version);
        public delegate IntPtr GetSteamMatchmakingDelegate(IntPtr user, IntPtr pipe, string version);
        public delegate IntPtr GetSteamMatchmakingServersDelegate(IntPtr user, IntPtr pipe, string version);
        public delegate IntPtr GetSteamGenericInterfaceDelegate(IntPtr user, IntPtr pipe, string version);
        public delegate IntPtr GetSteamUserStatsDelegate(IntPtr user, IntPtr pipe, string version);
        public delegate IntPtr GetSteamGameServerStatsDelegate(IntPtr user, IntPtr pipe, string version);
        public delegate IntPtr GetSteamAppsDelegate(IntPtr user, IntPtr pipe, string version);
        public delegate IntPtr GetSteamNetworkingDelegate(IntPtr user, IntPtr pipe, string version);
        public delegate IntPtr GetSteamRemoteStorageDelegate(IntPtr user, IntPtr pipe, string version);
        public delegate IntPtr GetSteamScreenshotsDelegate(IntPtr user, IntPtr pipe, string version);
        public delegate void RunFrameDelegate();
        public delegate uint GetIPCCallCountDelegate();
        public delegate void SetWarningMessageHookDelegate(IntPtr function);
        public delegate Boolean ShutdownIfAllPipesClosedDelegate();
        public delegate IntPtr GetSteamHTTPDelegate(IntPtr user, IntPtr pipe, string version);
        public delegate IntPtr GetSteamUnifiedMessagesDelegate(IntPtr user, IntPtr pipe, string version);
        public delegate IntPtr GetSteamControllerDelegate(IntPtr user, IntPtr pipe, string version);
        public delegate IntPtr GetSteamUGCDelegate(IntPtr user, IntPtr pipe, string version);
        public delegate IntPtr GetSteamAppListDelegate(IntPtr user, IntPtr pipe, string version);
        public delegate IntPtr GetSteamMusicDelegate(IntPtr user, IntPtr pipe, string version);
        public delegate IntPtr GetSteamMusicRemoteDelegate(IntPtr user, IntPtr pipe, string version);
        public delegate IntPtr GetSteamHTMLSurfaceDelegate(IntPtr user, IntPtr pipe, string version);
        public delegate void Set_SteamAPI_CPostAPIResultInProcessDelegate(IntPtr function);
        public delegate void Remove_SteamAPI_CPostAPIResultInProcessDelegate(IntPtr function);
        public delegate void Set_SteamAPI_CCheckCallbackRegisteredInProcessDelegate(IntPtr function);
        public delegate IntPtr GetSteamInventoryDelegate(IntPtr user, IntPtr pipe, string version);
        public delegate IntPtr GetSteamVideoDelegate(IntPtr user, IntPtr pipe, string version);
    }
}
