using System;
using System.Runtime.InteropServices;

// Autogenerated @ 06/08/18
namespace InterfaceGameServerStats
{
    /// <summary>
    /// Exports the delegates for all interfaces that implement SteamGameServerStats001
    /// </summary>
    [ArgonCore.Interface.Delegate(Name = "SteamGameServerStats001")]
    class SteamGameServerStats001_Delegates
    {
    }
}
