using System;
using System.Runtime.InteropServices;

// Autogenerated @ 19/07/18
namespace InterfaceController
{
    /// <summary>
    /// Exports the delegates for all interfaces that implement SteamController
    /// </summary>
    [ArgonCore.Interface.Delegate(Name = "SteamController")]
    class SteamController_Delegates
    {
    }
}
