using System;
using System.Runtime.InteropServices;

// Autogenerated @ 14/07/18
namespace InterfaceUGC
{
    /// <summary>
    /// Exports the delegates for all interfaces that implement SteamUGC
    /// </summary>
    [ArgonCore.Interface.Delegate(Name = "SteamUGC")]
    class SteamUGC_Delegates
    {
    }
}
