using System;
using System.Runtime.InteropServices;

// Autogenerated @ 14/07/18
namespace InterfaceHTMLSurface
{
    /// <summary>
    /// Exports the delegates for all interfaces that implement SteamHTMLSurface
    /// </summary>
    [ArgonCore.Interface.Delegate(Name = "SteamHTMLSurface")]
    class SteamHTMLSurface_Delegates
    {
    }
}
