using System;
using System.Runtime.InteropServices;

// Autogenerated @ 18/07/18
namespace InterfaceAppList
{
    /// <summary>
    /// Exports the delegates for all interfaces that implement SteamAppList
    /// </summary>
    [ArgonCore.Interface.Delegate(Name = "SteamAppList")]
    class SteamAppList_Delegates
    {
    }
}
