using System;

// Autogenerated @ 21/05/18
namespace IntefaceNetworking
{
    /// <summary>
    /// Implements the map for all interface SteamNetworking005
    /// </summary>
    [ArgonCore.Interface.Map(Name = "SteamNetworking005", Implements = "SteamNetworking")]
    public class SteamNetworking005_Map : ArgonCore.Interface.IBaseInterfaceMap
    {
    }
}
