using System;

// Autogenerated @ 24/05/18
namespace InterfaceMusicRemote
{
    /// <summary>
    /// Implements the map for interface SteamMusicRemote001
    /// </summary>
    [ArgonCore.Interface.Map(Name = "SteamMusicRemote001", Implements = "SteamMusicRemote")]
    public class SteamMusicRemote001_Map : ArgonCore.Interface.IBaseInterfaceMap
    {
    }
}
