using System;

// Autogenerated @ 21/05/18
namespace InterfaceRemoteStorage
{
    /// <summary>
    /// Implements the map for all interface SteamRemoteStorage014
    /// </summary>
    [ArgonCore.Interface.Map(Name = "SteamRemoteStorage014", Implements = "SteamRemoteStorage")]
    public class SteamRemoteStorage014_Map : ArgonCore.Interface.IBaseInterfaceMap
    {
    }
}
