using System;

// Autogenerated @ 09/06/18
namespace InterfaceMatchmakingServers
{
    /// <summary>
    /// Implements the map for interface SteamMatchmakingServers002
    /// </summary>
    [ArgonCore.Interface.Map(Name = "SteamMatchmakingServers002", Implements = "SteamMatchmakingServers")]
    public class SteamMatchmakingServers002_Map : ArgonCore.Interface.IBaseInterfaceMap
    {
    }
}
