using System;

// Autogenerated @ 01/06/18
namespace InterfaceMusic
{
    /// <summary>
    /// Implements the map for interface SteamMusic001
    /// </summary>
    [ArgonCore.Interface.Map(Name = "SteamMusic001", Implements = "SteamMusic")]
    public class SteamMusic001_Map : ArgonCore.Interface.IBaseInterfaceMap
    {
    }
}
