using System;

// Autogenerated @ 24/05/18
namespace InterfaceUtils
{
    /// <summary>
    /// Implements the map for interface SteamUtils009
    /// </summary>
    [ArgonCore.Interface.Map(Name = "SteamUtils009", Implements = "SteamUtils")]
    public class SteamUtils009_Map : ArgonCore.Interface.IBaseInterfaceMap
    {
    }
}
