using System;

// Autogenerated @ 21/05/18
namespace InterfaceMatchmaking
{
    /// <summary>
    /// Implements the map for all interface SteamMatchmaking009
    /// </summary>
    [ArgonCore.Interface.Map(Name = "SteamMatchmaking009", Implements = "SteamMatchmaking")]
    public class SteamMatchmaking009_Map : ArgonCore.Interface.IBaseInterfaceMap
    {
    }
}
