using System;

// Autogenerated @ 21/05/18
namespace InterfaceVideo
{
    /// <summary>
    /// Implements the map for all interface SteamVideo002
    /// </summary>
    [ArgonCore.Interface.Map(Name = "SteamVideo002", Implements = "SteamVideo")]
    public class SteamVideo002_Map : ArgonCore.Interface.IBaseInterfaceMap
    {
    }
}
