using System;

// Autogenerated @ 24/06/18
namespace InterfaceGameServer
{
    /// <summary>
    /// Implements the map for interface SteamGameServer012
    /// </summary>
    [ArgonCore.Interface.Map(Name = "SteamGameServer012", Implements = "SteamGameServer")]
    public class SteamGameServer012_Map : ArgonCore.Interface.IBaseInterfaceMap
    {
    }
}
