using System;

// Autogenerated @ 21/05/18
namespace InterfaceGameServer
{
    /// <summary>
    /// Implements the map for all interface SteamGameServer012
    /// </summary>
    [ArgonCore.Interface.Map(Name = "SteamGameServer012", Implements = "SteamGameServer")]
    public class SteamGameServer012_Map : ArgonCore.Interface.IBaseInterfaceMap
    {
    }
}
