using System;

// Autogenerated @ 21/05/18
namespace InterfaceGameServerStats
{
    /// <summary>
    /// Implements the map for all interface SteamGameServerStats001
    /// </summary>
    [ArgonCore.Interface.Map(Name = "SteamGameServerStats001", Implements = "SteamGameServerStats")]
    public class SteamGameServerStats001_Map : ArgonCore.Interface.IBaseInterfaceMap
    {
    }
}
