using System;

// Autogenerated @ 01/06/18
namespace InterfaceFriends
{
    /// <summary>
    /// Implements the map for interface SteamFriends001
    /// </summary>
    [ArgonCore.Interface.Map(Name = "SteamFriends001", Implements = "SteamFriends")]
    public class SteamFriends001_Map : ArgonCore.Interface.IBaseInterfaceMap
    {
        public string GetPersonaName(IntPtr _)
        {
            var f = new ArgonCore.IPC.SerializedFunction
            {
               ClientId = ClientId,
               InterfaceId = InterfaceId,
               Name = "GetPersonaName",
               Args = new object[] {},
            };
            return ArgonCore.IPC.ClientPipe.CallSerializedFunction<string>(PipeId, f);
        }
    }
}
