using System;

// Autogenerated @ 21/05/18
namespace InterfaceHTMLSurface
{
    /// <summary>
    /// Implements the map for all interface SteamHTMLSurface004
    /// </summary>
    [ArgonCore.Interface.Map(Name = "SteamHTMLSurface004", Implements = "SteamHTMLSurface")]
    public class SteamHTMLSurface004_Map : ArgonCore.Interface.IBaseInterfaceMap
    {
    }
}
