using System;

// Autogenerated @ 24/06/18
namespace InterfaceUnifiedMessages
{
    /// <summary>
    /// Implements the map for interface SteamUnifiedMessages001
    /// </summary>
    [ArgonCore.Interface.Map(Name = "SteamUnifiedMessages001", Implements = "SteamUnifiedMessages")]
    public class SteamUnifiedMessages001_Map : ArgonCore.Interface.IBaseInterfaceMap
    {
    }
}
