using System;

// Autogenerated @ 02/06/18
namespace InterfaceHTTP
{
    /// <summary>
    /// Implements the map for interface SteamHTTP002
    /// </summary>
    [ArgonCore.Interface.Map(Name = "SteamHTTP002", Implements = "SteamHTTP")]
    public class SteamHTTP002_Map : ArgonCore.Interface.IBaseInterfaceMap
    {
    }
}
