using System;

// Autogenerated @ 01/06/18
namespace InterfaceAppList
{
    /// <summary>
    /// Implements the map for interface SteamAppList001
    /// </summary>
    [ArgonCore.Interface.Map(Name = "SteamAppList001", Implements = "SteamAppList")]
    public class SteamAppList001_Map : ArgonCore.Interface.IBaseInterfaceMap
    {
    }
}
