using System;

// Autogenerated @ 10/06/18
namespace InterfaceUGC
{
    /// <summary>
    /// Implements the map for interface SteamUGC010
    /// </summary>
    [ArgonCore.Interface.Map(Name = "SteamUGC010", Implements = "SteamUGC")]
    public class SteamUGC010_Map : ArgonCore.Interface.IBaseInterfaceMap
    {
    }
}
