using System;

// Autogenerated @ 09/06/18
namespace InterfaceScreenshots
{
    /// <summary>
    /// Implements the map for interface SteamScreenshots003
    /// </summary>
    [ArgonCore.Interface.Map(Name = "SteamScreenshots003", Implements = "SteamScreenshots")]
    public class SteamScreenshots003_Map : ArgonCore.Interface.IBaseInterfaceMap
    {
    }
}
