using System;

// Autogenerated @ 23/05/18
namespace InterfaceController
{
    /// <summary>
    /// Implements the map for interface SteamController006
    /// </summary>
    [ArgonCore.Interface.Map(Name = "SteamController006", Implements = "SteamController")]
    public class SteamController006_Map : ArgonCore.Interface.IBaseInterfaceMap
    {
    }
}
