using System;

// Autogenerated @ 06/08/18
namespace InterfaceFriends
{
    /// <summary>
    /// Implements the map for interface CLIENTFRIENDS_INTERFACE_VERSION001
    /// </summary>
    [ArgonCore.Interface.Map(Name = "CLIENTFRIENDS_INTERFACE_VERSION001")]
    public class ClientFriends001_Map : ArgonCore.Interface.IBaseInterfaceMap
    {
        public string GetPersonaName(IntPtr _)
        {

            var result = Client.ClientPipe.CallSerializedFunction(PipeId, new ArgonCore.IPC.SerializedFunction()
            {
                ClientId = ClientId,
                InterfaceId = InterfaceId,
                Name = "GetPersonaName",
                Args = new object[] {},

            });



            return (string)result.Result;
        }
        public void SetPeronaName(IntPtr _, string name)
        {

            var result = Client.ClientPipe.CallSerializedFunction(PipeId, new ArgonCore.IPC.SerializedFunction()
            {
                ClientId = ClientId,
                InterfaceId = InterfaceId,
                Name = "SetPeronaName",
                Args = new object[] {name},

            });



        }
        public int SetPersonaNameEx(IntPtr _, string name, bool send_cb)
        {

            var result = Client.ClientPipe.CallSerializedFunction(PipeId, new ArgonCore.IPC.SerializedFunction()
            {
                ClientId = ClientId,
                InterfaceId = InterfaceId,
                Name = "SetPersonaNameEx",
                Args = new object[] {name, send_cb},

            });



            return (int)result.Result;
        }
        public bool IsPersonaNameSet(IntPtr _)
        {

            var result = Client.ClientPipe.CallSerializedFunction(PipeId, new ArgonCore.IPC.SerializedFunction()
            {
                ClientId = ClientId,
                InterfaceId = InterfaceId,
                Name = "IsPersonaNameSet",
                Args = new object[] {},

            });



            return (bool)result.Result;
        }
        public int GetPersonaState(IntPtr _)
        {

            var result = Client.ClientPipe.CallSerializedFunction(PipeId, new ArgonCore.IPC.SerializedFunction()
            {
                ClientId = ClientId,
                InterfaceId = InterfaceId,
                Name = "GetPersonaState",
                Args = new object[] {},

            });



            return (int)result.Result;
        }
        public void SetPersonaState(IntPtr _, SteamKit2.EPersonaState state)
        {

            var result = Client.ClientPipe.CallSerializedFunction(PipeId, new ArgonCore.IPC.SerializedFunction()
            {
                ClientId = ClientId,
                InterfaceId = InterfaceId,
                Name = "SetPersonaState",
                Args = new object[] {state},

            });



        }
    }
}
