using System;

// Autogenerated @ 21/08/18
namespace InterfaceMusic
{
    /// <summary>
    /// Implements the map for interface SteamMusic001
    /// </summary>
    [Core.Interface.Map(Name = "SteamMusic001")]
    public class SteamMusic001_Map : Core.Interface.IBaseInterfaceMap
    {
    }
}
