using System;

// Autogenerated @ 11/08/18
namespace InterfaceUserStats
{
    /// <summary>
    /// Implements the map for interface SteamUserStats011
    /// </summary>
    [ArgonCore.Interface.Map(Name = "SteamUserStats011")]
    public class SteamUserStats011_Map : ArgonCore.Interface.IBaseInterfaceMap
    {
    }
}
