using System;

// Autogenerated @ 14/07/18
namespace InterfaceUserStats
{
    /// <summary>
    /// Implements the map for interface SteamUserStats011
    /// </summary>
    [ArgonCore.Interface.Map(Name = "SteamUserStats011", Implements = "SteamUserStats")]
    public class SteamUserStats011_Map : ArgonCore.Interface.IBaseInterfaceMap
    {
    }
}
