using System;

// Autogenerated @ 21/08/18
namespace InterfaceMusicRemote
{
    /// <summary>
    /// Implements the map for interface SteamMusicRemote001
    /// </summary>
    [Core.Interface.Map(Name = "SteamMusicRemote001")]
    public class SteamMusicRemote001_Map : Core.Interface.IBaseInterfaceMap
    {
    }
}
