using System;

// Autogenerated @ 21/08/18
namespace InterfaceHTMLSurface
{
    /// <summary>
    /// Implements the map for interface SteamHTMLSurface004
    /// </summary>
    [Core.Interface.Map(Name = "SteamHTMLSurface004")]
    public class SteamHTMLSurface004_Map : Core.Interface.IBaseInterfaceMap
    {
    }
}
