using System;

// Autogenerated @ 21/08/18
namespace InterfaceGameServer
{
    /// <summary>
    /// Implements the map for interface SteamGameServer012
    /// </summary>
    [Core.Interface.Map(Name = "SteamGameServer012")]
    public class SteamGameServer012_Map : Core.Interface.IBaseInterfaceMap
    {
    }
}
