using System;

// Autogenerated @ 06/08/18
namespace InterfaceApps
{
    /// <summary>
    /// Implements the map for interface SteamApps008
    /// </summary>
    [ArgonCore.Interface.Map(Name = "SteamApps008")]
    public class SteamApps008_Map : ArgonCore.Interface.IBaseInterfaceMap
    {
    }
}
