using System;

// Autogenerated @ 21/08/18
namespace InterfaceUGC
{
    /// <summary>
    /// Implements the map for interface SteamUGC010
    /// </summary>
    [Core.Interface.Map(Name = "SteamUGC010")]
    public class SteamUGC010_Map : Core.Interface.IBaseInterfaceMap
    {
    }
}
