using System;

// Autogenerated @ 06/08/18
namespace InterfaceMatchmakingServers
{
    /// <summary>
    /// Implements the map for interface SteamMatchmakingServers002
    /// </summary>
    [ArgonCore.Interface.Map(Name = "SteamMatchmakingServers002")]
    public class SteamMatchmakingServers002_Map : ArgonCore.Interface.IBaseInterfaceMap
    {
    }
}
