using System;

// Autogenerated @ 21/08/18
namespace IntefaceNetworking
{
    /// <summary>
    /// Implements the map for interface SteamNetworking005
    /// </summary>
    [Core.Interface.Map(Name = "SteamNetworking005")]
    public class SteamNetworking005_Map : Core.Interface.IBaseInterfaceMap
    {
    }
}
