using System;

// Autogenerated @ 21/08/18
namespace InterfaceUnifiedMessages
{
    /// <summary>
    /// Implements the map for interface SteamUnifiedMessages001
    /// </summary>
    [Core.Interface.Map(Name = "SteamUnifiedMessages001")]
    public class SteamUnifiedMessages001_Map : Core.Interface.IBaseInterfaceMap
    {
    }
}
