using System;

// Autogenerated @ 06/08/18
namespace InterfaceHTTP
{
    /// <summary>
    /// Implements the map for interface SteamHTTP002
    /// </summary>
    [ArgonCore.Interface.Map(Name = "SteamHTTP002")]
    public class SteamHTTP002_Map : ArgonCore.Interface.IBaseInterfaceMap
    {
    }
}
