using System;

// Autogenerated @ 23/07/18
namespace InterfaceHTMLSurface
{
    /// <summary>
    /// Implements the map for interface SteamHTMLSurface004
    /// </summary>
    [ArgonCore.Interface.Map(Name = "SteamHTMLSurface004")]
    public class SteamHTMLSurface004_Map : ArgonCore.Interface.IBaseInterfaceMap
    {
    }
}
