using System;

// Autogenerated @ 21/08/18
namespace InterfaceAppList
{
    /// <summary>
    /// Implements the map for interface SteamAppList001
    /// </summary>
    [Core.Interface.Map(Name = "SteamAppList001")]
    public class SteamAppList001_Map : Core.Interface.IBaseInterfaceMap
    {
    }
}
