using System;

// Autogenerated @ 21/08/18
namespace InterfaceMatchmaking
{
    /// <summary>
    /// Implements the map for interface SteamMatchmaking009
    /// </summary>
    [Core.Interface.Map(Name = "SteamMatchmaking009")]
    public class SteamMatchmaking009_Map : Core.Interface.IBaseInterfaceMap
    {
    }
}
