using System;

// Autogenerated @ 21/08/18
namespace InterfaceController
{
    /// <summary>
    /// Implements the map for interface SteamController006
    /// </summary>
    [Core.Interface.Map(Name = "SteamController006")]
    public class SteamController006_Map : Core.Interface.IBaseInterfaceMap
    {
    }
}
