using System;

// Autogenerated @ 06/08/18
namespace InterfaceUnifiedMessages
{
    /// <summary>
    /// Implements the map for interface SteamUnifiedMessages001
    /// </summary>
    [ArgonCore.Interface.Map(Name = "SteamUnifiedMessages001")]
    public class SteamUnifiedMessages001_Map : ArgonCore.Interface.IBaseInterfaceMap
    {
    }
}
