using System;

// Autogenerated @ 11/08/18
namespace InterfaceScreenshots
{
    /// <summary>
    /// Implements the map for interface SteamScreenshots003
    /// </summary>
    [ArgonCore.Interface.Map(Name = "SteamScreenshots003")]
    public class SteamScreenshots003_Map : ArgonCore.Interface.IBaseInterfaceMap
    {
    }
}
