using System;

// Autogenerated @ 21/08/18
namespace InterfaceHTTP
{
    /// <summary>
    /// Implements the map for interface SteamHTTP002
    /// </summary>
    [Core.Interface.Map(Name = "SteamHTTP002")]
    public class SteamHTTP002_Map : Core.Interface.IBaseInterfaceMap
    {
    }
}
