using System;

// Autogenerated @ 21/08/18
namespace InterfaceVideo
{
    /// <summary>
    /// Implements the map for interface SteamVideo002
    /// </summary>
    [Core.Interface.Map(Name = "SteamVideo002")]
    public class SteamVideo002_Map : Core.Interface.IBaseInterfaceMap
    {
    }
}
