using System;

// Autogenerated @ 11/08/18
namespace InterfaceAppList
{
    /// <summary>
    /// Implements the map for interface SteamAppList001
    /// </summary>
    [ArgonCore.Interface.Map(Name = "SteamAppList001")]
    public class SteamAppList001_Map : ArgonCore.Interface.IBaseInterfaceMap
    {
    }
}
