using System;

// Autogenerated @ 21/08/18
namespace InterfaceScreenshots
{
    /// <summary>
    /// Implements the map for interface SteamScreenshots003
    /// </summary>
    [Core.Interface.Map(Name = "SteamScreenshots003")]
    public class SteamScreenshots003_Map : Core.Interface.IBaseInterfaceMap
    {
    }
}
