using System;

// Autogenerated @ 23/07/18
namespace InterfaceUGC
{
    /// <summary>
    /// Implements the map for interface SteamUGC010
    /// </summary>
    [ArgonCore.Interface.Map(Name = "SteamUGC010")]
    public class SteamUGC010_Map : ArgonCore.Interface.IBaseInterfaceMap
    {
    }
}
