using System;

// Autogenerated @ 23/07/18
namespace InterfaceVideo
{
    /// <summary>
    /// Implements the map for interface SteamVideo002
    /// </summary>
    [ArgonCore.Interface.Map(Name = "SteamVideo002")]
    public class SteamVideo002_Map : ArgonCore.Interface.IBaseInterfaceMap
    {
    }
}
