using System;

// Autogenerated @ 11/08/18
namespace InterfaceMusic
{
    /// <summary>
    /// Implements the map for interface SteamMusic001
    /// </summary>
    [ArgonCore.Interface.Map(Name = "SteamMusic001")]
    public class SteamMusic001_Map : ArgonCore.Interface.IBaseInterfaceMap
    {
    }
}
