using System;

// Autogenerated @ 23/07/18
namespace InterfaceGameServer
{
    /// <summary>
    /// Implements the map for interface SteamGameServer012
    /// </summary>
    [ArgonCore.Interface.Map(Name = "SteamGameServer012")]
    public class SteamGameServer012_Map : ArgonCore.Interface.IBaseInterfaceMap
    {
    }
}
