using System;

// Autogenerated @ 11/08/18
namespace InterfaceRemoteStorage
{
    /// <summary>
    /// Implements the map for interface SteamRemoteStorage014
    /// </summary>
    [ArgonCore.Interface.Map(Name = "SteamRemoteStorage014")]
    public class SteamRemoteStorage014_Map : ArgonCore.Interface.IBaseInterfaceMap
    {
    }
}
