using System;

// Autogenerated @ 19/07/18
namespace InterfaceRemoteStorage
{
    /// <summary>
    /// Implements the map for interface SteamRemoteStorage014
    /// </summary>
    [ArgonCore.Interface.Map(Name = "SteamRemoteStorage014", Implements = "SteamRemoteStorage")]
    public class SteamRemoteStorage014_Map : ArgonCore.Interface.IBaseInterfaceMap
    {
    }
}
