using System;

// Autogenerated @ 21/08/18
namespace InterfaceMatchmakingServers
{
    /// <summary>
    /// Implements the map for interface SteamMatchmakingServers002
    /// </summary>
    [Core.Interface.Map(Name = "SteamMatchmakingServers002")]
    public class SteamMatchmakingServers002_Map : Core.Interface.IBaseInterfaceMap
    {
    }
}
