using System;

// Autogenerated @ 21/07/18
namespace InterfaceInventory
{
    /// <summary>
    /// Implements the map for interface SteamInventory003
    /// </summary>
    [ArgonCore.Interface.Map(Name = "SteamInventory003", Implements = "SteamInventory")]
    public class SteamInventory003_Map : ArgonCore.Interface.IBaseInterfaceMap
    {
    }
}
