using System;

// Autogenerated @ 23/07/18
namespace InterfaceMatchmaking
{
    /// <summary>
    /// Implements the map for interface SteamMatchmaking009
    /// </summary>
    [ArgonCore.Interface.Map(Name = "SteamMatchmaking009")]
    public class SteamMatchmaking009_Map : ArgonCore.Interface.IBaseInterfaceMap
    {
    }
}
