using System;

// Autogenerated @ 23/07/18
namespace InterfaceGameServerStats
{
    /// <summary>
    /// Implements the map for interface SteamGameServerStats001
    /// </summary>
    [ArgonCore.Interface.Map(Name = "SteamGameServerStats001")]
    public class SteamGameServerStats001_Map : ArgonCore.Interface.IBaseInterfaceMap
    {
    }
}
