using System;

// Autogenerated @ 11/08/18
namespace IntefaceNetworking
{
    /// <summary>
    /// Implements the map for interface SteamNetworking005
    /// </summary>
    [ArgonCore.Interface.Map(Name = "SteamNetworking005")]
    public class SteamNetworking005_Map : ArgonCore.Interface.IBaseInterfaceMap
    {
    }
}
