using System;

// Autogenerated @ 06/08/18
namespace InterfaceMusicRemote
{
    /// <summary>
    /// Implements the map for interface SteamMusicRemote001
    /// </summary>
    [ArgonCore.Interface.Map(Name = "SteamMusicRemote001")]
    public class SteamMusicRemote001_Map : ArgonCore.Interface.IBaseInterfaceMap
    {
    }
}
