using System;

// Autogenerated @ 14/07/18
namespace IntefaceNetworking
{
    /// <summary>
    /// Implements the map for interface SteamNetworking005
    /// </summary>
    [ArgonCore.Interface.Map(Name = "SteamNetworking005", Implements = "SteamNetworking")]
    public class SteamNetworking005_Map : ArgonCore.Interface.IBaseInterfaceMap
    {
    }
}
