using System;

// Autogenerated @ 23/07/18
namespace InterfaceController
{
    /// <summary>
    /// Implements the map for interface SteamController006
    /// </summary>
    [ArgonCore.Interface.Map(Name = "SteamController006")]
    public class SteamController006_Map : ArgonCore.Interface.IBaseInterfaceMap
    {
    }
}
