using System;

// Autogenerated @ 21/08/18
namespace InterfaceRemoteStorage
{
    /// <summary>
    /// Implements the map for interface SteamRemoteStorage014
    /// </summary>
    [Core.Interface.Map(Name = "SteamRemoteStorage014")]
    public class SteamRemoteStorage014_Map : Core.Interface.IBaseInterfaceMap
    {
    }
}
