using System;

// Autogenerated @ 21/08/18
namespace InterfaceGameServerStats
{
    /// <summary>
    /// Implements the map for interface SteamGameServerStats001
    /// </summary>
    [Core.Interface.Map(Name = "SteamGameServerStats001")]
    public class SteamGameServerStats001_Map : Core.Interface.IBaseInterfaceMap
    {
    }
}
