using System;

// Autogenerated @ 05/05/18
namespace InterfaceSteamClient
{
    /// <summary>
    /// Exports the delegates for all interfaces that implement STEAMCLIENT_INTERFACE_VERSION
    /// </summary>
    [ArgonCore.InterfaceDelegate(Name = "STEAMCLIENT_INTERFACE_VERSION")]
    class STEAMCLIENT_INTERFACE_VERSION_Delegates
    {
        public delegate Int32 TestDelegate(String a, Int32 n);
        public delegate String Test2Delegate(String a, String b);
        public delegate Int32 Test3Delegate(String a, Int32 n);
        public delegate String Test4Delegate(String a, String b);
    }
}
