local p = premake
local project = p.project
local workspace = p.workspace
local tree = p.tree
local cmake = p.modules.cmake

cmake.workspace = {}
local m = cmake.workspace


-- Generate a cmake workspace
function m.generate(wks)
	p.utf8()
	_p('# This file is generated by premake5')
	_p('cmake_minimum_required(VERSION 3.1)')
	_p('set(WORKSPACE_NAME "%s")', wks.name)
	_p('project(${WORKSPACE_NAME})')
	_p('set(CMAKE_MODULE_PATH "${CMAKE_CURRENT_SOURCE_DIR}")')
	_p('')
	local tr = workspace.grouptree(wks)
	tree.traverse(tr, {
		onleaf = function(n)
			local prj = n.project
			_p('include(%s)', prj.name)
		end,

		onbranch = function(n)
			-- TODO: not sure what situation this appears...?
			-- premake5.lua emit's one of these for 'contrib', which is a top-level folder with the zip projects
		end,
	})
end
