using System;

// Autogenerated @ 20/05/18
namespace InterfaceSteamUser
{
    /// <summary>
    /// Exports the delegates for all interfaces that implement SteamUser
    /// </summary>
    [ArgonCore.Interface.Delegate(Name = "SteamUser")]
    class SteamUser_Delegates
    {
        public delegate IntPtr GetHSteamUserDelegate();
        public delegate void TestMemeDelegate();
        public delegate int TestMeme2Delegate(Int32[] arg);
    }
}
