using System;

// Autogenerated @ 20/05/18
namespace InterfaceSteamClient
{
    /// <summary>
    /// Exports the delegates for all interfaces that implement SteamClient
    /// </summary>
    [ArgonCore.Interface.Delegate(Name = "SteamClient")]
    class SteamClient_Delegates
    {
        public delegate uint CreateSteamPipeDelegate();
        public delegate bool ReleaseSteamPipeDelegate(uint pipe);
        public delegate uint ConnectToGlobalUserDelegate(uint pipe);
        public delegate uint CreateLocalUserDelegate(ref UInt32 user, uint account_type);
        public delegate void ReleaseUserDelegate(uint user, uint pipe);
        public delegate IntPtr GetSteamUserDelegate(uint user, uint pipe, string version);
        public delegate IntPtr GetSteamGameServerDelegate(uint user, uint pipe, string version);
        public delegate void SetLocalIPBindingDelegate(uint ip, uint port);
        public delegate IntPtr GetSteamFriendsDelegate(uint user, uint pipe, string version);
        public delegate IntPtr GetSteamUtilsDelegate(uint pipe, string version);
        public delegate IntPtr GetSteamMatchmakingDelegate(uint user, IntPtr pipe, string version);
        public delegate IntPtr GetSteamMatchmakingServersDelegate(uint user, IntPtr pipe, string version);
        public delegate IntPtr GetSteamGenericInterfaceDelegate(uint user, IntPtr pipe, string version);
        public delegate IntPtr GetSteamUserStatsDelegate(uint user, IntPtr pipe, string version);
        public delegate IntPtr GetSteamGameServerStatsDelegate(uint user, IntPtr pipe, string version);
        public delegate IntPtr GetSteamAppsDelegate(uint user, IntPtr pipe, string version);
        public delegate IntPtr GetSteamNetworkingDelegate(uint user, IntPtr pipe, string version);
        public delegate IntPtr GetSteamRemoteStorageDelegate(uint user, IntPtr pipe, string version);
        public delegate IntPtr GetSteamScreenshotsDelegate(uint user, IntPtr pipe, string version);
        public delegate void RunFrameDelegate();
        public delegate uint GetIPCCallCountDelegate();
        public delegate void SetWarningMessageHookDelegate(IntPtr function);
        public delegate bool ShutdownIfAllPipesClosedDelegate();
        public delegate IntPtr GetSteamHTTPDelegate(uint user, IntPtr pipe, string version);
        public delegate IntPtr GetSteamUnifiedMessagesDelegate(uint user, IntPtr pipe, string version);
        public delegate IntPtr GetSteamControllerDelegate(uint user, IntPtr pipe, string version);
        public delegate IntPtr GetSteamUGCDelegate(uint user, IntPtr pipe, string version);
        public delegate IntPtr GetSteamAppListDelegate(uint user, IntPtr pipe, string version);
        public delegate IntPtr GetSteamMusicDelegate(uint user, IntPtr pipe, string version);
        public delegate IntPtr GetSteamMusicRemoteDelegate(uint user, IntPtr pipe, string version);
        public delegate IntPtr GetSteamHTMLSurfaceDelegate(uint user, IntPtr pipe, string version);
        public delegate void Set_SteamAPI_CPostAPIResultInProcessDelegate(IntPtr function);
        public delegate void Remove_SteamAPI_CPostAPIResultInProcessDelegate(IntPtr function);
        public delegate void Set_SteamAPI_CCheckCallbackRegisteredInProcessDelegate(IntPtr function);
        public delegate IntPtr GetSteamInventoryDelegate(uint user, IntPtr pipe, string version);
        public delegate IntPtr GetSteamVideoDelegate(uint user, IntPtr pipe, string version);
    }
}
